[book]

authors = ["ashutosh"]
language = "en"
multilingual = false
src = "src"
title = "Shayri - शायरी "

[output.html]

default-theme = "light"
git-repository-url = "https://github.com/ashutoshmjain/rtm"
edit-url-template = "https://github.com/ashutoshmjain/rtm/edit/main/{path}"
cname = "poems.shutri.com"
no-section-label = true
