[book]

authors = ["ashutosh"]
language = "en"
multilingual = false
src = "src"
title = "Madan Maholvi - मदन महोलवी "

[output.html]

git-repository-url = "https://github.com/ashutoshmjain/rtm"
edit-url-template = "https://github.com/ashutoshmjain/rtm/edit/main/{path}"
cname = "poems.shutri.com"
no-section-label = true
