[book]

authors = ["madan maholvi"]
language = "en"
multilingual = false
src = "src"
title = "महोलवी नामा "

[output.html]
theme = "src/theme"

git-repository-url = "https://github.com/ashutoshmjain/rtm"
edit-url-template = "https://github.com/ashutoshmjain/rtm/edit/main/{path}"
cname = "poems.shutri.com"
no-section-label = true
