[book]

authors = ["ashutosh"]
language = "en"
multilingual = false
src = "src"
title = "Shayri"

[output.html]

google-analytics = "UA-90523130-2"
default-theme = "ayu"
git-repository-url = "https://github.com/ashutoshmjain/rtm"
edit-url-template = "https://github.com/ashutoshmjain/rtm/edit/main/{path}"
cname = "poems.shutri.com"
no-section-label = true 
